CREATE TABLE AUTHOR(
ID INT AUTO_INCREMENT,
NAME VARCHAR(255),
EMAIL VARCHAR(255) NOT NULL UNIQUE,
created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
);
CREATE TABLE AUTHOR_ADDRESS(
ID INT auto_increment,
CITY VARCHAR(255),
STREET VARCHAR(255),
AUTHOR_ID INT NOT NULL UNIQUE,
PRIMARY KEY (ID),
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
);
CREATE TABLE POST(
ID INT AUTO_INCREMENT,
TITLE VARCHAR(255) NOT NULL,
CONTENTS VARCHAR(300),
PRIMARY KEY (ID)
);
CREATE TABLE AUTHOR_POST(
ID INT AUTO_INCREMENT,
AUTHOR_ID INT,
POST_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
FOREIGN KEY (POST_ID) REFERENCES POST(ID)
); -- insert시 post와 트랜잭션으로 묶인다.


-- 강사님
CREATE TABLE AUTHOR(
ID INT AUTO_INCREMENT,
NAME VARCHAR(255),
EMAIL VARCHAR(255) NOT NULL,
created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID),
unique(email)
);
CREATE TABLE AUTHOR_ADDRESS(
ID INT auto_increment,
COUNTRY VARCHAR(255),
CITY VARCHAR(255),
STREET VARCHAR(255),
AUTHOR_ID INT NOT NULL,
PRIMARY KEY (ID),
unique(AUTHOR_ID),
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID) ON delete cascade
);
CREATE TABLE POST(
ID INT AUTO_INCREMENT,
TITLE VARCHAR(255) NOT NULL,
CONTENTS VARCHAR(300),
PRIMARY KEY (ID)
);
CREATE TABLE AUTHOR_POST(
ID INT AUTO_INCREMENT, PRIMARY KEY,
AUTHOR_ID INT NOT NULL,
POST_ID INT NOT NULL,
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
FOREIGN KEY (POST_ID) REFERENCES POST(ID)
); -- insert시 post와 트랜잭션으로 묶인다.